
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
  profiles:
    active: local
server:
  port: 8080
