spring:
  application:
    name: FrontendMicroservice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      file-size-threshold: 2KB
  profiles:
    active: local
server:
  port: 8089
  forward-headers-strategy: framework
