spring:
  application:
    name: AuthService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

  mvc:
    hidden method:
      filter:
        enabled: true
  profiles:
    active: local
server:
  port: 8086