spring:
  application:
    name: OrderService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  mvc:
    hidden method:
      filter:
        enabled: true
  profiles:
    active: local

server:
  port: 8084